### PR TITLE
[WIP] Biscuit 2.0 specification and samples

### PR DESCRIPTION
**Pull request by Geal**
See #72

### CODE REVIEW

**Comment by fbredy** [comment]
What about this V2 ? is it still "in progress" ?

**Comment by Geal** [comment]
@fbredy it is mostly done. Currently we're working on the [web components](https://github.com/biscuit-auth/biscuit-web-components) and the new [website](https://github.com/biscuit-auth/website), and will publish that along with the 2.0.

I'd like to see the java version done as well. Do you have plans to update the C# version to 2.0?

**Comment by fbredy** [comment]
> @fbredy it is mostly done. Currently we're working on the [web components](https://github.com/biscuit-auth/biscuit-web-components) and the new [website](https://github.com/biscuit-auth/website), and will publish that along with the 2.0.
> 
> I'd like to see the java version done as well. Do you have plans to update the C# version to 2.0?

@Geal, i'll update the C# biscuit package, just after the merge of this Pull Request. i've already started.

**Comment by Geal** [comment]
ok, I'm merging this now, there's been enough time to explore it :)

**Pull request merged**
